name: sys_dia_log
description: Blood pressure diary

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.7.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_i18n: ^0.32.4
  logging: ^1.1.0
  cupertino_icons: ^1.0.5
  auto_route: ^5.0.4
  numberpicker: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^4.3.1
  graphic: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  auto_route_generator: ^5.0.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/

flutter_icons:
  image_path_android: "assets/sys-dia-log-logo.png"
  image_path_ios: "assets/sys-dia-log-logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon
