name: "Release [tag]"
on:
  push:
    tags:
      - v*
permissions:
  contents: write

jobs:
  release-android:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.7.3"
          cache: true

      - name: Create Key
        env:
          KEY_JKS: ${{secrets.KEY_JKS}}
        run: echo $KEY_JKS | base64 -d > android/key.jks

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android App
        env:
          ALIAS: ${{secrets.ALIAS}}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        run: flutter build apk --release

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk-signed
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.RELEASE_TOKEN }}

